version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: fitme_admin
      POSTGRES_PASSWORD: FitMe123
      POSTGRES_DB: fitme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app_container
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://fitme_admin:FitMe123@db:5432/fitme_db
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
    depends_on:
      - app
    ports:
      - "8501:8501"

volumes:
  postgres_data:

